In [ ]:
import numpy as np 
from importlib import reload 

import regain.hmm.hmm_graphical_lasso; reload(regain.hmm.hmm_graphical_lasso)
from regain.hmm.hmm_graphical_lasso import HMM_GraphicalLasso

In [ ]:
X = np.random.randn(1000, 10)

In [ ]:
mdl = HMM_GraphicalLasso(verbose=True, mode='scaled')

In [ ]:
mdl.fit(X)

In [ ]:
mdl.labels_

In [ ]:
mdl.labels_

In [ ]:
mdl.precisions_

In [17]:
from importlib import reload
import regain.datasets.hmm; reload(regain.datasets.hmm)
from regain.datasets.hmm import generate_complementary_precisions_matrix

In [18]:
generate_complementary_precisions_matrix(n_dim_obs=5, n_states=3)

[]
[[1. 1. 0. 1. 0.]
 [1. 1. 0. 0. 1.]
 [0. 0. 1. 1. 1.]
 [1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1.]]
[(0, 1), (3, 2), (0, 0), (3, 3), (3, 0), (4, 4), (1, 4), (2, 4), (2, 3), (2, 2), (4, 2), (1, 0), (4, 1), (1, 1), (0, 3)]
[[1. 1. 0. 1. 0.]
 [1. 1. 0. 0. 1.]
 [0. 0. 1. 1. 1.]
 [1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1.]]
[[1. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[(0, 1), (1, 2), (3, 2), (0, 0), (3, 3), (3, 0), (0, 2), (4, 4), (1, 4), (2, 1), (2, 0), (2, 4), (2, 3), (2, 2), (4, 2), (1, 0), (4, 1), (1, 1), (0, 3)]


([array([[-0.33333333,  0.66666667, -0.33333333,  0.66666667, -0.33333333],
         [ 0.66666667, -0.33333333, -0.33333333, -0.33333333,  0.66666667],
         [-0.33333333, -0.33333333, -0.33333333,  0.66666667,  0.66666667],
         [ 0.66666667, -0.33333333,  0.66666667, -0.33333333, -0.33333333],
         [-0.33333333,  0.66666667,  0.66666667, -0.33333333, -0.33333333]]),
  array([[ 2.68751815e-16, -1.00000000e+00,  1.00000000e+00,
           0.00000000e+00,  0.00000000e+00],
         [-1.00000000e+00, -3.33066907e-16,  1.00000000e+00,
           0.00000000e+00,  0.00000000e+00],
         [ 1.00000000e+00,  1.00000000e+00, -1.00000000e+00,
           0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           1.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  1.00000000e+00]]),
  array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00

In [ ]:
a = ['a', 'b', 'c']
a.remove('a')

In [ ]:
a

In [ ]:
a.remove('a')

In [ ]:
a.remove??